format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbfs_v1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: USB_DEVICE_VBUS_SENSE_PIN_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: USB_VBUS_SENSE}
  - type: Integer
    attributes: {id: USB_DRIVER_RTOS_TASK_PRIORITY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '213', y: '309', id: drv_usbfs_v1}
