format_version: v1.0
type: UniqueComponent
attributes: {id: rtcc}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: RTCALRM_ARPT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: RTCC_ALARM_REPEAT_FOREVER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: RTCC_CLOCK_SOURCE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: RTCC_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: RTCTIME_DATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '181231'}
- type: ElementPosition
  attributes: {x: '49', y: '113', id: rtcc}
