format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIperf}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_IPERF_MAX_INSTANCES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_RX_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4096'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TX_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4096'}
- type: ElementPosition
  attributes: {x: '460', y: '21', id: tcpipIperf}
